- name: Install Docker Engine
  hosts: all
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Add packages to use https repository
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - gnupg-agent
        - software-properties-common

    - name: Add docker's official gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add dockers's repository
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker engine
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

- name: Open protocols and ports between the hosts
  hosts: all
  become: yes
  tasks:

    - name: Install firewall
      apt:
        name: firewalld
        state: present
    - name: Open necessary ports
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 2377/tcp
        - 7946/tcp
        - 7946/udp
        - 4789/udp

