image: ubuntu:bionic

variables:
  network: 'kvp_net1'

stages:
  - deploy

before_script:
  # setup ssh
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - 'eval $(ssh-agent -s)'
  - 'echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d "\r" | ssh-add - > /dev/null'
  - 'mkdir -p ~/.ssh'
  - 'chmod 700 ~/.ssh'
  - 'ssh-keyscan -t rsa $SSH_NODE >> ~/.ssh/known_hosts'
  - 'runcmd="ssh dubovsky@$SSH_NODE "'

clean_old:
  stage: deploy
  when: manual
  script:
    - '$runcmd "sudo docker stack rm kong || /bin/true"'
    - '$runcmd "sudo docker kill kong-database || /bin/true"'
    - '$runcmd "sudo docker rm kong-database || /bin/true"'

deploy:
  stage: deploy
  when: manual
  script:
    - 'dir=`$runcmd mktemp -d`'
    - 'scp start_kong.sh kong.yml dubovsky@$SSH_NODE:$dir'
    - '$runcmd sudo bash $dir/start_kong.sh'

